version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - zabbix-var-lib-data:/var/lib/data
      - zabbix-var-lib-mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - zabbix-alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '8082:8080'
      - '8443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - mysql
   
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:latest
    user: root
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=zabbix
      - ZBX_SERVER_HOST=zabbix-server

networks:
  network-zabbix:
    driver: bridge

volumes:
  zabbix-var-lib-data:
  zabbix-var-lib-mysql:
  zabbix-alertscripts:
